name: Steam Workshop Upload

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install steamcmd
        run: |
          sudo apt-get update
          sudo apt-get install -y steamcmd

      - name: Upload to Steam Workshop
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        run: |
          ./steamcmd.sh +login ${{ env.STEAM_USERNAME }} ${{ env.STEAM_PASSWORD }} \
          +workshop_build_item metadata.vdf +quit

      - name: Logout from Steam
        run: |
          ./steamcmd.sh +logout
