name: Reformat and Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  reformat_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run reformat script
        run: python scripts/reformat.py

      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code || echo "Changes detected"

      - name: Commit and push changes
        if: steps.changes.outputs.result == 'Changes detected'
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Reformatted files"
          git push origin main
