name: Update from upstream

on:
  schedule:
    - cron: "0 0 * * *" # Minden nap éjfélkor fut

jobs:
  update-repo:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == true
    permissions:
      contents: write
    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add upstream repository
        run: git remote add upstream https://github.com/rkorom/hoi4-hun.git

      - name: Fetch upstream repository
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes
        run: git push origin main
