name: Update from upstream

on:
  schedule:
    - cron: "0 0 * * *" # Minden nap éjfélkor fut

permissions:
  contents: write

jobs:
  update-repo:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == true
    steps:
      - name: Checkout the forked repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/rkorom/hoi4-hun.git

      - name: Fetch upstream repository
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes
        run: git push origin main
